use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct RectF {
    pub x: f32,
    pub y: f32,
    pub width: f32,
    pub height: f32,
}

impl RectF {
    pub fn new(x: f32, y: f32, width: f32, height: f32) -> Self {
        Self {
            x,
            y,
            width,
            height,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct Color {
    pub r: f32,
    pub g: f32,
    pub b: f32,
    pub a: f32,
}

impl Color {
    pub fn rgba(r: f32, g: f32, b: f32, a: f32) -> Self {
        Self { r, g, b, a }
    }

    pub fn rgb(r: f32, g: f32, b: f32) -> Self {
        Self { r, g, b, a: 1.0 }
    }

    pub fn from_u8(r: u8, g: u8, b: u8, a: u8) -> Self {
        Self {
            r: r as f32 / 255.0,
            g: g as f32 / 255.0,
            b: b as f32 / 255.0,
            a: a as f32 / 255.0,
        }
    }
}

/// Vector and text draw commands generated by widget render passes.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum DrawCommand {
    Clear {
        color: Color,
    },
    DrawRect {
        rect: RectF,
        color: Color,
        corner_radius: f32,
    },
    DrawText {
        text: String,
        font_family: String,
        font_size: f32,
        rect: RectF,
        color: Color,
    },
    DrawImage {
        resource_id: String,
        rect: RectF,
        opacity: f32,
    },
    PushClip {
        rect: RectF,
    },
    PopClip,
}

/// 2. Rendering API Pillar Interface
pub trait RenderCanvas: Send + Sync {
    /// Clears canvas area with color.
    fn clear(&mut self, color: Color);
    /// Draws a filled rectangle with optional rounded corners.
    fn draw_rect(&mut self, rect: RectF, color: Color, corner_radius: f32);
    /// Draws formatted text within bounding box.
    fn draw_text(
        &mut self,
        text: &str,
        font_family: &str,
        font_size: f32,
        rect: RectF,
        color: Color,
    );
    /// Draws an image asset.
    fn draw_image(&mut self, resource_id: &str, rect: RectF, opacity: f32);
    /// Pushes clipping bounds for partial invalidation.
    fn push_clip(&mut self, rect: RectF);
    /// Pops active clipping region.
    fn pop_clip(&mut self);
    /// Invalidates region for dirty rect partial rendering.
    fn invalidate(&mut self, rect: RectF);
    /// Returns queued draw commands for current frame.
    fn commands(&self) -> &[DrawCommand];
}

/// In-memory batching render canvas buffer.
#[derive(Debug, Default)]
pub struct BatchRenderCanvas {
    commands: Vec<DrawCommand>,
    dirty_regions: Vec<RectF>,
}

impl BatchRenderCanvas {
    pub fn new() -> Self {
        Self::default()
    }
}

impl RenderCanvas for BatchRenderCanvas {
    fn clear(&mut self, color: Color) {
        self.commands.push(DrawCommand::Clear { color });
    }

    fn draw_rect(&mut self, rect: RectF, color: Color, corner_radius: f32) {
        self.commands.push(DrawCommand::DrawRect {
            rect,
            color,
            corner_radius,
        });
    }

    fn draw_text(
        &mut self,
        text: &str,
        font_family: &str,
        font_size: f32,
        rect: RectF,
        color: Color,
    ) {
        self.commands.push(DrawCommand::DrawText {
            text: text.to_string(),
            font_family: font_family.to_string(),
            font_size,
            rect,
            color,
        });
    }

    fn draw_image(&mut self, resource_id: &str, rect: RectF, opacity: f32) {
        self.commands.push(DrawCommand::DrawImage {
            resource_id: resource_id.to_string(),
            rect,
            opacity,
        });
    }

    fn push_clip(&mut self, rect: RectF) {
        self.commands.push(DrawCommand::PushClip { rect });
    }

    fn pop_clip(&mut self) {
        self.commands.push(DrawCommand::PopClip);
    }

    fn invalidate(&mut self, rect: RectF) {
        self.dirty_regions.push(rect);
    }

    fn commands(&self) -> &[DrawCommand] {
        &self.commands
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_render_canvas_batching() {
        let mut canvas = BatchRenderCanvas::new();
        canvas.clear(Color::rgba(0.0, 0.0, 0.0, 1.0));
        canvas.draw_rect(
            RectF::new(0.0, 0.0, 100.0, 50.0),
            Color::rgba(1.0, 0.0, 0.0, 1.0),
            4.0,
        );
        canvas.draw_text(
            "CPU 45%",
            "Segoe UI",
            14.0,
            RectF::new(10.0, 10.0, 80.0, 20.0),
            Color::rgba(1.0, 1.0, 1.0, 1.0),
        );

        assert_eq!(canvas.commands().len(), 3);
    }
}
