[package]
name = "plugin_runtime"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
windows = { workspace = true }
ipc_protocol = { path = "../ipc_protocol" }
thiserror.workspace = true
tracing.workspace = true
anyhow.workspace = true
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["sync", "time", "process"] }

